### ISSUE TITLE
해찬님 소스코드 리뷰

### ISSUE THREAD

**Issue by Bebeqwer** [haechanlee96/blog#1]
public interface PostRepository extends JpaRepository<Post,Long> {
    List<Post> findAllByOrderByModifiedAtDesc();   
   
}

 List<Posting> findAllByOrderByCreatedAtDesc(); 로 고쳐서 코드상에서 
   의미를 조금 더 명확하게 하는것도 괜찮을거 같아요 기능상의 차이는 아마 없을거 같습니다

 @Transactional
    public Long updatePost(Long id, RequestDto requestDto){ //게시글 수정
        // 해당 메모 DB에 존재 확인
        Post post = findPost(id);

        // 해당 내용 수정
        post.update(requestDto);
        return id;
    }

    public Long deletePost(Long id) {
        // 해당 메모 DB에 존재 확인
        Post post = findPost(id);

        // 해당 내용 수정
        postRepository.delete(post);
        return id;
    }

업데이트와 딜리트 하는 과정에서 비밀번호를 체크하는 기능이 빠져있어요 나중에 추가하시면 좋을거 같아요

**Comment by haechanlee96** [comment]
감사합니다!
